#
# Copyright (C) 2026 The Android Open Source Project
#
# SPDX-License-Identifier: Apache-2.0
#
# 从 songyuan 的 device.mk 派生。凡带 TODO 的条目都是 athens 需要单独取证的地方，
# 取证方法写在注释里，不要用 songyuan 的值顶替。
#

# Audio
# ⚠️ 必须放在 common inherit **之前**：同一个目标路径，PRODUCT_COPY_FILES 里先出现的赢，
#    而 common 会装 AOSP 的 default_volume_tables.xml。
# VERIFIED —— configs/audio/default_volume_tables.xml 是 athens 原厂
# /vendor/etc/default_volume_tables.xml 的逐字节副本（129 行，md5 d3faec95e0929c100c89487a0e948d51），
# 不是 songyuan 的调参版。
# ⚠️ 原厂 vendor/build.prop 里另有 ro.config.media_vol_steps=150 / media_vol_default=100，
#    公共树用的是 15 / 10。本 ROM 沿用公共树的值 —— 音量表定义的是**曲线形状**，
#    与步数相互独立，所以两者不冲突。想改成原厂的 150 步需要在此处显式覆写，
#    但要先想清楚 150 级滑块在手机上的手感。
PRODUCT_COPY_FILES += \
    $(LOCAL_PATH)/configs/audio/default_volume_tables.xml:$(TARGET_COPY_OUT_VENDOR)/etc/default_volume_tables.xml \
    $(LOCAL_PATH)/configs/audio/audio_policy_volumes.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_policy_volumes.xml \
    hardware/qcom-caf/sm8850/audio/primary-hal/configs/common/bluetooth_qti_hearing_aid_audio_policy_configuration.xml:$(TARGET_COPY_OUT_VENDOR)/etc/bluetooth_qti_hearing_aid_audio_policy_configuration.xml

# Inherit from sm8850-common
# The source V2 HAL forwards AOSP touch events to the athens Goodix module.
TARGET_USES_STOCK_FINGERPRINT := false
# Keep the installed Gunyah pvmfw during initial bring-up. Do not advertise
# protected VMs or include the AOSP AVF stack until that combination is tested.
TARGET_DISABLE_AVF := true
$(call inherit-product, device/xiaomi/sm8850-common/common.mk)

PRODUCT_AVF_ENABLED := false
PRODUCT_BUILD_PVMFW_IMAGE := false

# The stock PAL BtA2dp backend also handles LE Audio and rejects external
# device connections when the A2DP offload gate is disabled.
PRODUCT_VENDOR_PROPERTIES += persist.bluetooth.a2dp_offload.disabled=false

# Get non-open-source specific aspects (generated by extract-files.py, not in manifest)
$(call inherit-product, vendor/xiaomi/athens/athens-vendor.mk)

# libhardware requires a .default.so alias for the stock Goodix module.
PRODUCT_PACKAGES += fingerprint.goodix_us2.default_symlink

# Camera
# allocator V1：实测（对清单内 3400 条目标路径逐个 readelf -dW）**只剩 2 个消费者**
#   vendor/lib64/camera/components/com.qti.node.dewarp.so
#   vendor/lib64/vendor.qti.hardware.camera.offlinecamera-service-impl.so
# 而这两个正是 extract-files.py 里被 V1→V2 改写的对象。也就是说 fixup 生效后，
# V1 在**已提取的 blob 集合**里已无消费者。仍然保留这一条，理由是取证范围有限：
# 扫描只覆盖"清单里的 blob"，不覆盖**源码构建**的消费者（如 QTI 的
# vendor.qti.hardware.display.allocator-service），那部分要等 sync 完才能查。
# P4 复核：若 build 后确认无人需要，可删掉以省体积。
PRODUCT_PACKAGES += \
    android.hardware.graphics.allocator-V1-ndk.vendor \
    vendor.qti.hardware.camera.offlinecamera-V2-ndk.vendor

# Display
# Exact built-in panel ID and brightness-to-nits calibration from athens stock.
PRODUCT_COPY_FILES += \
    $(LOCAL_PATH)/configs/display/display_id_4630946928389601939.xml:$(TARGET_COPY_OUT_VENDOR)/etc/displayconfig/display_id_4630946928389601939.xml

# VERIFIED —— composer3 的版本从 athens 自己的 blob 上读出来，不是照抄 songyuan：
#   readelf -dW .../vendor/bin/hw/vendor.qti.hardware.display.composer-service
#   → NEEDED: android.hardware.graphics.composer3-V4-ndk.so
#             vendor.qti.hardware.display.composer3-V4-ndk.so
#             android.hardware.graphics.allocator-V2-ndk.so
# 公共树已经装了 Android 侧的 V4（common.mk:144），但 **QTI 侧装的是 V1**
# （common.mk:150 vendor.qti.hardware.display.composer3-V1-ndk.vendor），所以这里补 V4。
# 两台设备的 QTI V1 在 athens 上实测**零引用**（扫遍清单内全部 ELF），保留它不影响正确性。
#
# ⚠️ 全清单无人需要 allocator V1 之外的旧图形接口，也不要把 V1 无差别换成 V2/V4 ——
#    目标库存在只是必要条件，接口代次必须与消费者 NEEDED 对齐。
PRODUCT_PACKAGES += \
    vendor.qti.hardware.display.composer3-V4-ndk.vendor

# Lights
# 后置 LED 的 AIDL 实现（模块 android.hardware.light-service.sm8850）在 **sm8850-common**
# 里，不在设备树 —— 设备树只负责启用。
# 已取证（2026-09-27）：athens 原厂 rc 引用了六个 LED 节点 ——
#   leds/red、leds/green、leds/blue（三色 → athens 是 RGB 通知灯，不是纯白灯）
#   leds/amber:flash-2、leds/white:flash-1、leds/yellow:flash-0（三颗闪光灯）
# 所以灯是存在的，这也反证了 songyuan 的 ro.vendor.light.white_only=true 不该照抄
# （见 BoardConfig.mk 里那段说明）。
# TODO: 还剩一步 —— 读 common 的 aidl/light/Devices.cpp，确认它的 sysfs 路径表覆盖
#   athens 这六个节点。不符时再决定是扩展 common 还是自带一份。
# PRODUCT_PACKAGES += \
#     android.hardware.light-service.sm8850

# Init
PRODUCT_COPY_FILES += \
    $(LOCAL_PATH)/configs/init/init.athens.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.athens.rc

# Properties
# 机型相关的 odm 属性走 BoardConfig.mk 的 TARGET_ODM_PROP，由构建合并进生成的
# /odm/etc/build.prop，不在这里单独拷文件。
#
# ❌ 故意没有 songyuan 的 odm_CN.prop / odm_GL.prop：
#   songyuan 的区域机制是 odm.prop 里 `import /odm/etc/odm_${ro.boot.hwc}.prop`，
#   它把这两个文件拷进 /odm/etc/ 给 import 用。athens 的区域机制**不同** ——
#   原厂 odm/etc/build.prop:33 用 ${ro.boot.product.hardware.sku}_${ro.boot.ptcountrycode}
#   拼文件名，且那三个变体（athens_{jp,ru,tr}_build.prop）除产品名外只有
#   ro.*_for_attestation 与认证指纹。对解锁 BL 的 LineageOS 无意义，故不移植。
#   完整依据见 configs/properties/odm.prop 末尾。

# Soong namespaces
PRODUCT_SOONG_NAMESPACES += \
    $(LOCAL_PATH)

# Updater: OTA feed. 仓库待建（songyuan 的做法是把 zip 放 SourceForge，喂一个 raw JSON）。
# 在 OTA 仓库存在之前不要打开 —— 打开会指向 404。
# PRODUCT_SYSTEM_EXT_PROPERTIES += \
#     lineage.updater.uri=https://raw.githubusercontent.com/YuanHuakk/athens-ota/main/{device}.json

# Device overlays. Apply the 24dp corner inset once in the status bar.
# The Compose collapsed shade header also consumes this inset and 4dp top
# padding. Framework overlay supplies the power profile.
PRODUCT_PACKAGES += \
    FrameworksResAthens \
    SystemUIResAthens

# Temporary bring-up logs, installed through normal init imports. Recovery keeps
# its own startup script; no ro.boot.init_rc override is used.
ifneq (,$(filter eng userdebug,$(TARGET_BUILD_VARIANT)))
PRODUCT_COPY_FILES += \
    device/xiaomi/athens/configs/bringup/init.athens-diagnostics.rc:$(TARGET_COPY_OUT_SYSTEM)/etc/init/init.athens-diagnostics.rc \
    device/xiaomi/athens/configs/bringup/collect.sh:$(TARGET_COPY_OUT_SYSTEM)/bin/athens-collect.sh
endif

# IFAA: athens uses the stock AIDL mlipay service and ultrasonic FOD.
PRODUCT_PACKAGES += IFAAService
PRODUCT_VENDOR_PROPERTIES += persist.vendor.sys.pay.ifaa=1

# Stock athens camera with the app-local AOSP compatibility fixes validated on
# this vendor baseline. Keep Aperture available alongside it.
PRODUCT_PACKAGES += MiuiCameraAthens
